name: my_flow workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: hello world
        run: echo "hello world"
        shell: bash
  
  second_job:
    runs_on: ubuntu-latest
    steps:
      - name: goodbye world
        run : echo "goodbye world"
        shell: bash
